import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Weather from './components/Weather';
import Loading from './components/Loading';

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const apiKey = process.env.NEXT_PUBLIC_WEATHER_KEY;
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${apiKey}`;

  const getWeather = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      const response = await axios.get(url);
      setWeather(response.data);
    } catch (error) {
      console.error(error);
    }

    setCity('');
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Weather - Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* Overlay */}
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
      {/* Background image */}
      <Image
        src='https://images.unsplash.com/photo-1569511735406-407c5884625c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80'
        fill
        alt='weatherbackground'
      />

      {/* Search */}
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
        <form
          onSubmit={getWeather}

        >
          <div>
            <input
              onChange={(e) => setCity(e.target.value)}
              type='text'
              placeholder='Search city'
              value={city}
            />
          </div>
          <button type='submit'>
          </button>
        </form>
      </div>

      {/* Weather */}
      {loading ? <Loading /> : weather.main && <Weather data={weather} />}
    </div>
  );
}
